### ISSUE TITLE
rulesDirectory setup doesn't work

### ISSUE THREAD

**Issue by markyleong** [electroma/tslint-forbidden-imports#2]
Using `node_modules/tslint-forbidden-imports` in `tslint.json` `rulesDirectory` didn't work for me.

Output from running `ng lint` was:

```
Could not find implementations for the following rules specified in the configuration:
    forbidden-imports
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

I had to change it to `node_modules/tslint-forbidden-imports/dist` for it to work.

tslint version: 5.9.1

**Comment by electroma** [comment]
Fixed by #3. Version 1.0.5 is out.
@markyleong please upgrade and change `rulesDir` to `node_modules/tslint-forbidden-imports/rules`.
